=== luissilva1044894/hirez-api-docs/api/search-players/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://api.paladins.com/paladinsapi.svc/searchplayersjson",
    "type": "array",
    "title": "'search-players' schema",
    "description": "Schema for paladins/smite 'searchplayersJSON' endpoint",
    "default": {},
    "items": {
      "type": "object",
      "properties": {
        "ret_msg": {
          "type": [
            "string",
            "null"
          ],
          "examples": [
            "Approved",
            "Invalid Signature"
          ]
        },
        "Name": {
          "type": "string"
        },
        "player_id": {
          "type": "string"
        },
        "hz_player_name": {
          "type": [
            "string",
            "null"
          ]
        },
        "portal_id": {
          "type": "string"
        },
        "privacy_flag": {
          "type": "string"
        }
      },
      "required": [
        "Name",
        "hz_player_name",
        "player_id",
        "portal_id",
        "privacy_flag",
        "ret_msg"
      ],
      "additionalProperties": false
    },
    "examples": [
      [
        {
          "Name": "Death",
          "hz_player_name": null,
          "player_id": "3720661",
          "portal_id": "22",
          "privacy_flag": "n",
          "ret_msg": null
        },
        {
          "Name": "Death",
          "hz_player_name": "Death",
          "player_id": "13059270",
          "portal_id": "5",
          "privacy_flag": "n",
          "ret_msg": null
        }
      ]
    ]
  }

=== luissilva1044894/hirez-api-docs/api/search-players/smite.json
[
  {
    "Name":"Incon",
    "hz_player_name":"Incon",
    "player_id":"599339",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incon",
    "hz_player_name":null,
    "player_id":"700998977",
    "portal_id":"10",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incon",
    "hz_player_name":null,
    "player_id":"707067779",
    "portal_id":"22",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"incon1",
    "hz_player_name":"incon1",
    "player_id":"10997973",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"incon2",
    "hz_player_name":"incon2",
    "player_id":"12414091",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incon2032",
    "hz_player_name":"Incon2032",
    "player_id":"7523064",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incon2075",
    "hz_player_name":"Incon2075",
    "player_id":"14105108",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"INCON52",
    "hz_player_name":"INCON52",
    "player_id":"3030418",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incon5545",
    "hz_player_name":"Incon5545",
    "player_id":"5455660",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incon7",
    "hz_player_name":"Incon7",
    "player_id":"896471",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"incon890",
    "hz_player_name":"incon890",
    "player_id":"11070196",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconadorJoelPT",
    "hz_player_name":"InconadorJoelPT",
    "player_id":"27137",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconadorNesPT",
    "hz_player_name":"InconadorNesPT",
    "player_id":"37799",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconah",
    "hz_player_name":"inconah",
    "player_id":"11029514",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconaks",
    "hz_player_name":"inconaks",
    "player_id":"673528",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconakss",
    "hz_player_name":"Inconakss",
    "player_id":"5767519",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconation",
    "hz_player_name":"Inconation",
    "player_id":"13446269",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconBeard",
    "hz_player_name":"InconBeard",
    "player_id":"12446089",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconBot",
    "hz_player_name":"InconBot",
    "player_id":"13938224",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"INCONBR",
    "hz_player_name":"INCONBR",
    "player_id":"12363895",
    "portal_id":"1",
    "privacy_flag":"y",
    "ret_msg":null
  },
  {
    "Name":"Inconce1vable",
    "hz_player_name":"Inconce1vable",
    "player_id":"6719145",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconceivab1e",
    "hz_player_name":"Inconceivab1e",
    "player_id":"6930978",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconceivable",
    "hz_player_name":"Inconceivable",
    "player_id":"243991",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconceivableBak",
    "hz_player_name":"InconceivableBak",
    "player_id":"11478375",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconceivible",
    "hz_player_name":"Inconceivible",
    "player_id":"8621914",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconcent",
    "hz_player_name":"Inconcent",
    "player_id":"8196625",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconcessus",
    "hz_player_name":"Inconcessus",
    "player_id":"797919",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconcievabl",
    "hz_player_name":"inconcievabl",
    "player_id":"5786899",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inConcievable",
    "hz_player_name":"inConcievable",
    "player_id":"2026328",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconcious",
    "hz_player_name":"Inconcious",
    "player_id":"8670548",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconCLEAVEable",
    "hz_player_name":"InconCLEAVEable",
    "player_id":"7232422",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconclusive",
    "hz_player_name":"Inconclusive",
    "player_id":"2883758",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconclusive368",
    "hz_player_name":"Inconclusive368",
    "player_id":"5788808",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconcordia",
    "hz_player_name":"inconcordia",
    "player_id":"706865962",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconcucion",
    "hz_player_name":"inconcucion",
    "player_id":"712766103",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incondeaaaaahhh",
    "hz_player_name":"Incondeaaaaahhh",
    "player_id":"14104518",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"incondicional",
    "hz_player_name":"incondicional",
    "player_id":"11672023",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incondite",
    "hz_player_name":"Incondite",
    "player_id":"839741",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incondites",
    "hz_player_name":"Incondites",
    "player_id":"2200855",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconditus",
    "hz_player_name":"Inconditus",
    "player_id":"288868",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"incondizionalcj",
    "hz_player_name":"incondizionalcj",
    "player_id":"707457608",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incondor",
    "hz_player_name":"Incondor",
    "player_id":"9849935",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconected56266",
    "hz_player_name":"inconected56266",
    "player_id":"710052545",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"IncOnegin1",
    "hz_player_name":"IncOnegin1",
    "player_id":"11463831",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconel",
    "hz_player_name":"Inconel",
    "player_id":"2447452",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconFake",
    "hz_player_name":"InconFake",
    "player_id":"7284722",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconFan",
    "hz_player_name":"InconFan",
    "player_id":"12218698",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconFanClub",
    "hz_player_name":"InconFanClub",
    "player_id":"12651055",
    "portal_id":"5",
    "privacy_flag":"y",
    "ret_msg":null
  },
  {
    "Name":"InconFeeds",
    "hz_player_name":"InconFeeds",
    "player_id":"10759542",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconfens",
    "hz_player_name":"inconfens",
    "player_id":"13328375",
    "portal_id":"5",
    "privacy_flag":"y",
    "ret_msg":null
  },
  {
    "Name":"Inconfessus",
    "hz_player_name":"Inconfessus",
    "player_id":"8260119",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconFlex",
    "hz_player_name":"InconFlex",
    "player_id":"7295760",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InConflict",
    "hz_player_name":"InConflict",
    "player_id":"8634943",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InConForMaDo",
    "hz_player_name":"InConForMaDo",
    "player_id":"4505464",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"InconFormados",
    "hz_player_name":"InconFormados",
    "player_id":"9336880",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconforme",
    "hz_player_name":"inconforme",
    "player_id":"4461615",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconformities",
    "hz_player_name":"Inconformities",
    "player_id":"13351671",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Inconformity",
    "hz_player_name":"Inconformity",
    "player_id":"12637379",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"inconfundabil",
    "hz_player_name":"inconfundabil",
    "player_id":"8818376",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incongito",
    "hz_player_name":"Incongito",
    "player_id":"5696765",
    "portal_id":"1",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
    "Name":"Incongnitio",
    "hz_player_name":"Incongnitio",
    "player_id":"8966944",
    "portal_id":"5",
    "privacy_flag":"y",
    "ret_msg":null
  },
  {
    "Name":"incongnitoxd",
    "hz_player_name":"incongnitoxd",
    "player_id":"708826896",
    "portal_id":"5",
    "privacy_flag":"n",
    "ret_msg":null
  },
  {
